/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ContaPedidosRouteImport } from './routes/conta.pedidos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminCampanhasRouteImport } from './routes/admin.campanhas'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as PedidoIdConfirmacaoRouteImport } from './routes/pedido.$id.confirmacao'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ContaRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/admin/campanhas',
  path: '/admin/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/admin/produtos/',
  path: '/admin/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdConfirmacaoRoute = PedidoIdConfirmacaoRouteImport.update({
  id: '/pedido/$id/confirmacao',
  path: '/pedido/$id/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/admin/produtos/$id',
  path: '/admin/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/pedido/$id/confirmacao': typeof PedidoIdConfirmacaoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/pedido/$id/confirmacao': typeof PedidoIdConfirmacaoRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/pedido/$id/confirmacao': typeof PedidoIdConfirmacaoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/esqueci-senha'
    | '/login'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/conta/pedidos'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/pedido/$id/confirmacao'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/esqueci-senha'
    | '/login'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/conta/pedidos'
    | '/produto/$slug'
    | '/admin'
    | '/admin/produtos/$id'
    | '/pedido/$id/confirmacao'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/esqueci-senha'
    | '/login'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/conta/pedidos'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/pedido/$id/confirmacao'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  PedidoIdConfirmacaoRoute: typeof PedidoIdConfirmacaoRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/admin/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/admin/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id/confirmacao': {
      id: '/pedido/$id/confirmacao'
      path: '/pedido/$id/confirmacao'
      fullPath: '/pedido/$id/confirmacao'
      preLoaderRoute: typeof PedidoIdConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/admin/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContaRouteChildren {
  ContaPedidosRoute: typeof ContaPedidosRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaPedidosRoute: ContaPedidosRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  PedidoIdConfirmacaoRoute: PedidoIdConfirmacaoRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
