/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocaRouteImport } from './routes/troca'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MeiosDePagamentoRouteImport } from './routes/meios-de-pagamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DevolucaoRouteImport } from './routes/devolucao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CondicoesDeUsoRouteImport } from './routes/condicoes-de-uso'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as InstitucionalSlugRouteImport } from './routes/institucional.$slug'
import { Route as ContaPedidosRouteImport } from './routes/conta.pedidos'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutPendingRouteImport } from './routes/checkout.pending'
import { Route as CheckoutFailureRouteImport } from './routes/checkout.failure'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminContactMessagesRouteImport } from './routes/admin.contact-messages'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminCampanhasRouteImport } from './routes/admin.campanhas'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as AdminInstitutionalPagesIndexRouteImport } from './routes/admin.institutional-pages.index'
import { Route as PedidoIdConfirmacaoRouteImport } from './routes/pedido.$id.confirmacao'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as AdminSettingsFreteLocalRouteImport } from './routes/admin.settings.frete-local'
import { Route as AdminSettingsCompanyRouteImport } from './routes/admin.settings.company'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as AdminPedidosOrderIdRouteImport } from './routes/admin.pedidos.$orderId'
import { Route as AdminInstitutionalPagesIdRouteImport } from './routes/admin.institutional-pages.$id'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago.webhook'

const TrocaRoute = TrocaRouteImport.update({
  id: '/troca',
  path: '/troca',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MeiosDePagamentoRoute = MeiosDePagamentoRouteImport.update({
  id: '/meios-de-pagamento',
  path: '/meios-de-pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucaoRoute = DevolucaoRouteImport.update({
  id: '/devolucao',
  path: '/devolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicoesDeUsoRoute = CondicoesDeUsoRouteImport.update({
  id: '/condicoes-de-uso',
  path: '/condicoes-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalSlugRoute = InstitucionalSlugRouteImport.update({
  id: '/institucional/$slug',
  path: '/institucional/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ContaRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPendingRoute = CheckoutPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailureRoute = CheckoutFailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/admin/seguranca',
  path: '/admin/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/admin/contact-messages',
  path: '/admin/contact-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/admin/campanhas',
  path: '/admin/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/admin/produtos/',
  path: '/admin/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitutionalPagesIndexRoute =
  AdminInstitutionalPagesIndexRouteImport.update({
    id: '/admin/institutional-pages/',
    path: '/admin/institutional-pages/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PedidoIdConfirmacaoRoute = PedidoIdConfirmacaoRouteImport.update({
  id: '/pedido/$id/confirmacao',
  path: '/pedido/$id/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsFreteLocalRoute = AdminSettingsFreteLocalRouteImport.update({
  id: '/admin/settings/frete-local',
  path: '/admin/settings/frete-local',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsCompanyRoute = AdminSettingsCompanyRouteImport.update({
  id: '/admin/settings/company',
  path: '/admin/settings/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/admin/produtos/$id',
  path: '/admin/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosOrderIdRoute = AdminPedidosOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminInstitutionalPagesIdRoute =
  AdminInstitutionalPagesIdRouteImport.update({
    id: '/admin/institutional-pages/$id',
    path: '/admin/institutional-pages/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/condicoes-de-uso': typeof CondicoesDeUsoRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/devolucao': typeof DevolucaoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/meios-de-pagamento': typeof MeiosDePagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/troca': typeof TrocaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/checkout/failure': typeof CheckoutFailureRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/institucional/$slug': typeof InstitucionalSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/institutional-pages/$id': typeof AdminInstitutionalPagesIdRoute
  '/admin/pedidos/$orderId': typeof AdminPedidosOrderIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/settings/company': typeof AdminSettingsCompanyRoute
  '/admin/settings/frete-local': typeof AdminSettingsFreteLocalRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/pedido/$id/confirmacao': typeof PedidoIdConfirmacaoRoute
  '/admin/institutional-pages/': typeof AdminInstitutionalPagesIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/condicoes-de-uso': typeof CondicoesDeUsoRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/devolucao': typeof DevolucaoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/meios-de-pagamento': typeof MeiosDePagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/troca': typeof TrocaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/checkout/failure': typeof CheckoutFailureRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/institucional/$slug': typeof InstitucionalSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/institutional-pages/$id': typeof AdminInstitutionalPagesIdRoute
  '/admin/pedidos/$orderId': typeof AdminPedidosOrderIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/settings/company': typeof AdminSettingsCompanyRoute
  '/admin/settings/frete-local': typeof AdminSettingsFreteLocalRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/pedido/$id/confirmacao': typeof PedidoIdConfirmacaoRoute
  '/admin/institutional-pages': typeof AdminInstitutionalPagesIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/condicoes-de-uso': typeof CondicoesDeUsoRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/devolucao': typeof DevolucaoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/meios-de-pagamento': typeof MeiosDePagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/troca': typeof TrocaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/checkout/failure': typeof CheckoutFailureRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/institucional/$slug': typeof InstitucionalSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/institutional-pages/$id': typeof AdminInstitutionalPagesIdRoute
  '/admin/pedidos/$orderId': typeof AdminPedidosOrderIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/settings/company': typeof AdminSettingsCompanyRoute
  '/admin/settings/frete-local': typeof AdminSettingsFreteLocalRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/pedido/$id/confirmacao': typeof PedidoIdConfirmacaoRoute
  '/admin/institutional-pages/': typeof AdminInstitutionalPagesIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/condicoes-de-uso'
    | '/conta'
    | '/contato'
    | '/devolucao'
    | '/esqueci-senha'
    | '/login'
    | '/meios-de-pagamento'
    | '/privacidade'
    | '/reembolso'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/troca'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/contact-messages'
    | '/admin/cupons'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/admin/seguranca'
    | '/checkout/failure'
    | '/checkout/pending'
    | '/checkout/success'
    | '/conta/pedidos'
    | '/institucional/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/institutional-pages/$id'
    | '/admin/pedidos/$orderId'
    | '/admin/produtos/$id'
    | '/admin/settings/company'
    | '/admin/settings/frete-local'
    | '/api/public/csp-report'
    | '/api/public/health'
    | '/pedido/$id/confirmacao'
    | '/admin/institutional-pages/'
    | '/admin/produtos/'
    | '/api/public/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/condicoes-de-uso'
    | '/conta'
    | '/contato'
    | '/devolucao'
    | '/esqueci-senha'
    | '/login'
    | '/meios-de-pagamento'
    | '/privacidade'
    | '/reembolso'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/troca'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/contact-messages'
    | '/admin/cupons'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/admin/seguranca'
    | '/checkout/failure'
    | '/checkout/pending'
    | '/checkout/success'
    | '/conta/pedidos'
    | '/institucional/$slug'
    | '/produto/$slug'
    | '/admin'
    | '/admin/institutional-pages/$id'
    | '/admin/pedidos/$orderId'
    | '/admin/produtos/$id'
    | '/admin/settings/company'
    | '/admin/settings/frete-local'
    | '/api/public/csp-report'
    | '/api/public/health'
    | '/pedido/$id/confirmacao'
    | '/admin/institutional-pages'
    | '/admin/produtos'
    | '/api/public/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/condicoes-de-uso'
    | '/conta'
    | '/contato'
    | '/devolucao'
    | '/esqueci-senha'
    | '/login'
    | '/meios-de-pagamento'
    | '/privacidade'
    | '/reembolso'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/troca'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/contact-messages'
    | '/admin/cupons'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/admin/seguranca'
    | '/checkout/failure'
    | '/checkout/pending'
    | '/checkout/success'
    | '/conta/pedidos'
    | '/institucional/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/institutional-pages/$id'
    | '/admin/pedidos/$orderId'
    | '/admin/produtos/$id'
    | '/admin/settings/company'
    | '/admin/settings/frete-local'
    | '/api/public/csp-report'
    | '/api/public/health'
    | '/pedido/$id/confirmacao'
    | '/admin/institutional-pages/'
    | '/admin/produtos/'
    | '/api/public/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CondicoesDeUsoRoute: typeof CondicoesDeUsoRoute
  ContaRoute: typeof ContaRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DevolucaoRoute: typeof DevolucaoRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  MeiosDePagamentoRoute: typeof MeiosDePagamentoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrocaRoute: typeof TrocaRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  InstitucionalSlugRoute: typeof InstitucionalSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInstitutionalPagesIdRoute: typeof AdminInstitutionalPagesIdRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminSettingsCompanyRoute: typeof AdminSettingsCompanyRoute
  AdminSettingsFreteLocalRoute: typeof AdminSettingsFreteLocalRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  PedidoIdConfirmacaoRoute: typeof PedidoIdConfirmacaoRoute
  AdminInstitutionalPagesIndexRoute: typeof AdminInstitutionalPagesIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troca': {
      id: '/troca'
      path: '/troca'
      fullPath: '/troca'
      preLoaderRoute: typeof TrocaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meios-de-pagamento': {
      id: '/meios-de-pagamento'
      path: '/meios-de-pagamento'
      fullPath: '/meios-de-pagamento'
      preLoaderRoute: typeof MeiosDePagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devolucao': {
      id: '/devolucao'
      path: '/devolucao'
      fullPath: '/devolucao'
      preLoaderRoute: typeof DevolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condicoes-de-uso': {
      id: '/condicoes-de-uso'
      path: '/condicoes-de-uso'
      fullPath: '/condicoes-de-uso'
      preLoaderRoute: typeof CondicoesDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/$slug': {
      id: '/institucional/$slug'
      path: '/institucional/$slug'
      fullPath: '/institucional/$slug'
      preLoaderRoute: typeof InstitucionalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/pending': {
      id: '/checkout/pending'
      path: '/pending'
      fullPath: '/checkout/pending'
      preLoaderRoute: typeof CheckoutPendingRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failure': {
      id: '/checkout/failure'
      path: '/failure'
      fullPath: '/checkout/failure'
      preLoaderRoute: typeof CheckoutFailureRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/admin/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/admin/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/admin/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/admin/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutional-pages/': {
      id: '/admin/institutional-pages/'
      path: '/admin/institutional-pages'
      fullPath: '/admin/institutional-pages/'
      preLoaderRoute: typeof AdminInstitutionalPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id/confirmacao': {
      id: '/pedido/$id/confirmacao'
      path: '/pedido/$id/confirmacao'
      fullPath: '/pedido/$id/confirmacao'
      preLoaderRoute: typeof PedidoIdConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/frete-local': {
      id: '/admin/settings/frete-local'
      path: '/admin/settings/frete-local'
      fullPath: '/admin/settings/frete-local'
      preLoaderRoute: typeof AdminSettingsFreteLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/company': {
      id: '/admin/settings/company'
      path: '/admin/settings/company'
      fullPath: '/admin/settings/company'
      preLoaderRoute: typeof AdminSettingsCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/admin/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos/$orderId': {
      id: '/admin/pedidos/$orderId'
      path: '/$orderId'
      fullPath: '/admin/pedidos/$orderId'
      preLoaderRoute: typeof AdminPedidosOrderIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/institutional-pages/$id': {
      id: '/admin/institutional-pages/$id'
      path: '/admin/institutional-pages/$id'
      fullPath: '/admin/institutional-pages/$id'
      preLoaderRoute: typeof AdminInstitutionalPagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutFailureRoute: typeof CheckoutFailureRoute
  CheckoutPendingRoute: typeof CheckoutPendingRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutFailureRoute: CheckoutFailureRoute,
  CheckoutPendingRoute: CheckoutPendingRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ContaRouteChildren {
  ContaPedidosRoute: typeof ContaPedidosRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaPedidosRoute: ContaPedidosRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

interface AdminPedidosRouteChildren {
  AdminPedidosOrderIdRoute: typeof AdminPedidosOrderIdRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosOrderIdRoute: AdminPedidosOrderIdRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CondicoesDeUsoRoute: CondicoesDeUsoRoute,
  ContaRoute: ContaRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DevolucaoRoute: DevolucaoRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  MeiosDePagamentoRoute: MeiosDePagamentoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrocaRoute: TrocaRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminSegurancaRoute: AdminSegurancaRoute,
  InstitucionalSlugRoute: InstitucionalSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInstitutionalPagesIdRoute: AdminInstitutionalPagesIdRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminSettingsCompanyRoute: AdminSettingsCompanyRoute,
  AdminSettingsFreteLocalRoute: AdminSettingsFreteLocalRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  PedidoIdConfirmacaoRoute: PedidoIdConfirmacaoRoute,
  AdminInstitutionalPagesIndexRoute: AdminInstitutionalPagesIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
